### ISSUE TITLE
Consensys reading logged data failed

### ISSUE THREAD

**Issue by StudentofGermany** [seemoo-lab/pyshimmer#2]
Hello lumagi,

I use your Python API for my Shimmer3 EXG Unit and it works well. Thank you for that :)
Now I want to get the data from the Shimmer SD with Consensys. Sometimes it works, but more often an error occur.
Also I use your Reader API, but with the reader API the data have a different shape, like the streaming data.  And i would prefer to have the data in the shape of the output from Consensys. 
Could it be that the data got damaged or not closed with the Python API? Even if i use the stop() and shutdown() command? 

Best StudentofGermany

**Comment by lumagi** [comment]
> Also I use your Reader API, but with the reader API the data have a different shape, like the streaming data.

Could you elaborate on what exactly you mean by that? Do you mean that the data has a different shape as compared to the streamed data or the Consensys output? If the later is the case, you can simply use the `numpy.stack` or `numpy.concatenate`functions to merge the data columns into a 2D array.

> Could it be that the data got damaged or not closed with the Python API? Even if i use the stop() and shutdown() command?

Is it just the shape or also the values that are different? You should also be aware that both Consensys and the Reader API optionally perform post-processing. In the `ShimmerReader` class, consider the `post_process` constructor flag to enable or disable post-processing of the values.

**Comment by StudentofGermany** [comment]
The Excel File that I export with the Shimmer Software Consesys has the values of:
`
Shimmer_86A5_Timestamp_Unix_CAL | Shimmer_86A5_Accel_LN_X_CAL | Shimmer_86A5_Accel_LN_Y_CAL | Shimmer_86A5_Accel_LN_Z_CAL | Shimmer_86A5_Accel_WR_X_CAL | Shimmer_86A5_Accel_WR_Y_CAL | Shimmer_86A5_Accel_WR_Z_CAL | Shimmer_86A5_Battery_CAL | Shimmer_86A5_ECG_EMG_Status1_CAL | Shimmer_86A5_ECG_EMG_Status2_CAL | Shimmer_86A5_ECG_LA-RA_24BIT_CAL | Shimmer_86A5_ECG_LL-LA_24BIT_CAL | Shimmer_86A5_ECG_LL-RA_24BIT_CAL | Shimmer_86A5_ECG_RESP_24BIT_CAL | Shimmer_86A5_ECG_Vx-RL_24BIT_CAL | Shimmer_86A5_Ext_Exp_A15_CAL | Shimmer_86A5_Gyro_X_CAL | Shimmer_86A5_Gyro_Y_CAL | Shimmer_86A5_Gyro_Z_CAL | Shimmer_86A5_Mag_X_CAL | Shimmer_86A5_Mag_Y_CAL | Shimmer_86A5_Mag_Z_CAL | Shimmer_86A5_Pressure_BMP280_CAL | Shimmer_86A5_Temperature_BMP280_CAL`

but with the Reader API or the Streaming API i have only the channels:

`[<EChannelType.TIMESTAMP: 42>, <EChannelType.ACCEL_LN_X: 1>, <EChannelType.ACCEL_LN_Y: 2>, <EChannelType.ACCEL_LN_Z: 3>, <EChannelType.ACCEL_LSM303DLHC_X: 5>, <EChannelType.ACCEL_LSM303DLHC_Y: 6>, <EChannelType.ACCEL_LSM303DLHC_Z: 7>, <EChannelType.EXG_ADS1292R_1_STATUS: 30>, <EChannelType.EXG_ADS1292R_1_CH1_24BIT: 31>, <EChannelType.EXG_ADS1292R_1_CH2_24BIT: 32>, <EChannelType.EXG_ADS1292R_2_STATUS: 33>, <EChannelType.EXG_ADS1292R_2_CH1_24BIT: 34>, <EChannelType.EXG_ADS1292R_2_CH2_24BIT: 35>]`

so for example i don t have an ECG_Channel and the values are different to the values of the EXG_Channel.

**Comment by lumagi** [comment]
The Shimmer ECG device features two ADS1292R chips that do the AD conversion of the ECG channels. Each of these two chips samples two differential channels, which are called ExG1_CH1, ExG1_CH2, ExG2_CH1, ExG2_CH2. This is the data channels that the Reader and Streaming API see. They ExG channels themselves do not carry any information as to what electrodes are connected to each channel. This is determined by the built-in multiplexers of the ADS1292R chips and can be configured manually via the configuration file or automatically with the Consensys software. If you have configured your device for ECG sensing in Consensys, you can find the correct mapping between raw ExG channels and the corresponding logical ECG channels in Section 3.2 of the [ECG User Guide](http://www.shimmersensing.com/images/uploads/docs/ECG_User_Guide_Rev1.12.pdf).
Also, as an alternative, you can simply stream the data to your computer or your phone and try out the different electrode combinations to determine which ECG channel is recorded by which ExG channel.

I advise you to take a look at the following documentation for further information. The ECG and EMG devices have the same hardware and only differ in their multiplexer settings. This might give you a better idea how the AD chips operate.
* [Shimmer ECG Documentation](http://www.shimmersensing.com/images/uploads/docs/ECG_User_Guide_Rev1.12.pdf)
* [Shimmer EMG Documentation](http://www.shimmersensing.com/images/uploads/docs/EMG_User_Guide_Rev1.12.pdf)
* [The ADS1292R Chip Documentation](http://www.ti.com/lit/ds/symlink/ads1292r.pdf)

**Comment by lumagi** [comment]
Please let me know if this solves the issue of the different values. I have implemented multiple tests to verify that the results of the Reader API are equal to the output of Consensys, but that's of course not foolproof. If you're certain that you have found the right mapping between the columns in the Consensys output and the Reader output and the results still differ, please let me know.

**Comment by lumagi** [comment]
I also noticed that there are multiple channels missing from the Reader API channel list. Could you post the `sdlog.cfg` file of your Shimmer device?

**Comment by StudentofGermany** [comment]
Hello Lumagi,

the sdlog.cfg is:

`accel=1
gyro=0
mag=0
exg1_24bit=1
exg2_24bit=1
gsr=0
extch7=0
extch6=0
br_amp=0
vbat=0
accel_d=1
extch15=0
intch1=0
intch12=0
intch13=0
intch14=0
accel_mpu=0
mag_mpu=0
exg1_16bit=0
exg2_16bit=0
pres_bmp280=0
sample_rate=504.12
mg_internal_rate=0
mg_range=0
acc_internal_rate=7
accel_mpu_range=0
pres_bmp280_prec=0
gsr_range=4
exp_power=1
gyro_range=1
gyro_samplingrate=255
acc_range=0
acc_lpm=0
acc_hrm=1
user_button_enable=1
rtc_error_enable=1
sd_error_enable=1
iammaster=0
sync=0
low_battery_autostop=0
tcxo=0
interval=54
myid=0
Nshimmer=0
shimmername=Shimmer_86A5
experimentid=default_exp
configtime=1620377189
baud_rate=9
derived_channels=0
max_exp_len=0
EXG_ADS1292R_1_CONFIG1=3
EXG_ADS1292R_1_CONFIG2=168
EXG_ADS1292R_1_LOFF=16
EXG_ADS1292R_1_CH1SET=64
EXG_ADS1292R_1_CH2SET=64
EXG_ADS1292R_1_RLD_SENS=45
EXG_ADS1292R_1_LOFF_SENS=0
EXG_ADS1292R_1_LOFF_STAT=0
EXG_ADS1292R_1_RESP1=2
EXG_ADS1292R_1_RESP2=3
EXG_ADS1292R_2_CONFIG1=3
EXG_ADS1292R_2_CONFIG2=160
EXG_ADS1292R_2_LOFF=16
EXG_ADS1292R_2_CH1SET=64
EXG_ADS1292R_2_CH2SET=71
EXG_ADS1292R_2_RLD_SENS=0
EXG_ADS1292R_2_LOFF_SENS=0
EXG_ADS1292R_2_LOFF_STAT=0
EXG_ADS1292R_2_RESP1=2
EXG_ADS1292R_2_RESP2=1`

I think there are missing some Channels because of the configuration I did in Consensys. I just need for my task the EXG and the acceleration Channels.  I found out how the ECG values are composed:
`Shimmer_86A5_ECG_LA-RA_24BIT_CAL -> EChannelType.EXG_ADS1292R_1_CH2_24BIT
Shimmer_86A5_ECG_LL-LA_24BIT_CAL -> Shimmer_86A5_ECG_LA-RA_24BIT_CAL - Shimmer_86A5_ECG_LL-RA_24BIT_CAL
Shimmer_86A5_ECG_LL-RA_24BIT_CAL -> EChannelType.EXG_ADS1292R_1_CH1_24BIT
Shimmer_86A5_ECG_RESP_24BIT_CAL -> EChannelType.EXG_ADS1292R_2_CH1_24BIT
Shimmer_86A5_ECG_Vx-RL_24BIT_CAL -> EChannelType.EXG_ADS1292R_2_CH2_24BI`
Now I will do my own test with the shimmer Reader API and Consensys. I will let you know the results and close this if everything works :)
Thank you for your help again.

**Comment by StudentofGermany** [comment]
Hello Lumagi,
thank you for your help. 
Consensys unfortunately still does not manage to read all the data, but in the cases where no error occurs the data seems to match. Therefore, it is enough for me to be able to read the data using the Reader API and thus close the question
