### ISSUE TITLE
New Shimmer hardware revision 3R

### ISSUE THREAD

**Issue by lumagi** [seemoo-lab/pyshimmer#24]
![image](https://github.com/user-attachments/assets/154a9737-6ac0-432e-9a47-03b2f8b930c9)

Please find above a general overview of the changes for the IMUs. The things to note:-
- the raw sensor format (e.g. gyro in this case) can change between HW (e.g. Shimmer 3 vs Shimmer3r) versions
- we would like to add two additional sensors, the high g accel (200G) and the wide range mag, and in future may add other sensors (e.g. microphone etc)
- the high g accel format is custom
- just so you are aware we’ve had multiple revisions of Shimmer3 with different (_imu_) chips being used, but this we can help address (_if issues are raised_)
- it would be better for the front facing elements of the API to use user friendly names

I think the most important is just to build a general understanding of how the API wants to manage different hardware versions. Once we reach an agreement we can pick up from wherever you left off. Appreciate the help. Thanks.

_Originally posted by @ShimmerEngineering in https://github.com/seemoo-lab/pyshimmer/issues/22#issuecomment-2782131596_

**Comment by lumagi** [comment]
I have done a bit of reviewing regarding the planned changes you mentioned in the PR. I have a couple of questions, I would kindly ask you to comment on:
* Am I understanding correctly that you're extending the config Bytes from 4 to 7? Does this also affect the binary format of the files?
* In the Python API, I use several enums to identify the sensors and channels, see `ESensorGroup` and `EChannelType`. Am I understanding correctly that the new accelerometer / gyroscope / magnetometer chips will use the same channel and sensor indices in the binary files and the Inquiry response?

**Comment by ShimmerEngineering** [comment]
yes correct we are extending it to hold more configurations. for the binary file header this is the format for the 3R. so the new size for the header is 384 bytes for the 3R

![Image](https://github.com/user-attachments/assets/7190790d-41af-43ac-8a06-44d18e20d608)

![Image](https://github.com/user-attachments/assets/18040f74-5649-48df-9ad2-49e084216111)

however please note, we have not finalized the designed for the sdlog(binary file) header. We are thinking of adding the Channel ID sequence (_similar to the inquiry response_) to the sdlog(binary) file header. So the parsing order of the bytes in the binary file will be determined through said Channel ID sequence. I will notify as soon as its been finalized.

the same channel ID values will be used for both shimmer 3 and the 3R. e.g. channel ID = 0 will be the LN Accel X Axis for Shimmer3 and Shimmer3R. I hope that covers your questions, do not hesitate if you have other or follow up questions.

**Comment by lumagi** [comment]
I have been thinking on it for a little while. I think the best way to move forward is to continue with your suggestion of renaming the channel types to a user-friendly version that is sensor agnostic. I will need to refactor all the channel and data type mappings in the `dev` package to encapsulate it in a dedicated class. This class is aware of the shimmer hardware type and can map from logical channel types to the underlying data types and lengths. The Reader and Bluetooth classes will need to instantiate it once they know what HW and SW version is being used. Then they can query all HW/SW specific information from the class instance.

**Comment by ShimmerEngineering** [comment]
hi @lumagi I think that makes sense. thanks. let us know if we can help.

**Comment by lumagi** [comment]
@ShimmerEngineering I just formatted the code base with black to have a consistent code style. Since this affects all forks and future pull requests, I would advise you to pull the current `main` branch again.

**Comment by lumagi** [comment]
@ShimmerEngineering I have tried renaming the `EChannelType` instances to something less chip-reliant. But there seem to be more acceleration / mag / gyro channels than in your screenshot. Would you be willing to shed some light on the different channels and their use cases? The contents of `EChannelType` are mostly based on:
https://github.com/ShimmerResearch/shimmer3/blob/8fa04982b70877d88a40aaa12c342774c862bd34/LogAndStream/shimmer_btsd.h#L186-L192
Perhaps we could take this list as a reference?

**Comment by JongChern** [comment]
<html xmlns:v="urn:schemas-microsoft-com:vml"
xmlns:o="urn:schemas-microsoft-com:office:office"
xmlns:x="urn:schemas-microsoft-com:office:excel"
xmlns="http://www.w3.org/TR/REC-html40">

<head>

<meta name=ProgId content=Excel.Sheet>
<meta name=Generator content="Microsoft Excel 15">
<link id=Main-File rel=Main-File
href="file:///C:/Users/JC/AppData/Local/Temp/msohtmlclip1/01/clip.htm">
<link rel=File-List
href="file:///C:/Users/JC/AppData/Local/Temp/msohtmlclip1/01/clip_filelist.xml">

</head>

<body link="#467886" vlink="#96607D">

Shimmer3|Channel ID|User Friendly Name
-- | -- | --
X_A_ACCEL | 0x00 | Low Noice Accelerometer
Y_A_ACCEL | 0x01 | Low Noice Accelerometer
Z_A_ACCEL | 0x02 | Low Noice Accelerometer
VBATT | 0x03 | VSenseBatt
X_LSM303DLHC_ACCEL | 0x04 | Wide Range Accelerometer
Y_LSM303DLHC_ACCEL | 0x05 | Wide Range Accelerometer
Z_LSM303DLHC_ACCEL | 0x06 | Wide Range Accelerometer
X_LSM303DLHC_MAG | 0x07 | Magnetometer
Y_LSM303DLHC_MAG | 0x08 | Magnetometer
Z_LSM303DLHC_MAG | 0x09 | Magnetometer
X_MPU9150_GYRO | 0x0A | Gyroscope
Y_MPU9150_GYRO | 0x0B | Gyroscope
Z_MPU9150_GYRO | 0x0C | Gyroscope
EXTERNAL_ADC_7 | 0x0D | External ADC A0
EXTERNAL_ADC_6 | 0x0E | External ADC A1
EXTERNAL_ADC_15 | 0x0F | External ADC A2
INTERNAL_ADC_1 | 0x10 | Internal ADC A3
INTERNAL_ADC_12 | 0x11 | Internal ADC A0
INTERNAL_ADC_13 | 0x12 | Internal ADC A1
INTERNAL_ADC_14 | 0x13 | Internal ADC A2
X_MPU9150_ACCEL | 0x14 | High G Accelerometer
Y_MPU9150_ACCEL | 0x15 | High G Accelerometer
Z_MPU9150_ACCEL | 0x16 | High G Accelerometer
X_MPU9150_MAG | 0x17 | Wide Range Magnetometer
Y_MPU9150_MAG | 0x18 | Wide Range Magnetometer
Z_MPU9150_MAG | 0x19 | Wide Range Magnetometer
BMPX80_TEMP | 0x1A | Temperature
BMPX80_PRESSURE | 0x1B | Pressure
GSR_RAW | 0x1C | GSR
EXG_ADS1292R_1_STATUS | 0x1D | EXG1 Status
EXG_ADS1292R_1_CH1_24BIT | 0x1E | EXG1 CH1
EXG_ADS1292R_1_CH2_24BIT | 0x1F | EXG1 CH2
EXG_ADS1292R_2_STATUS | 0x20 | EXG2 Status
EXG_ADS1292R_2_CH1_24BIT | 0x21 | EXG2 CH1
EXG_ADS1292R_2_CH2_24BIT | 0x22 | EXG2 CH2
EXG_ADS1292R_1_CH1_16BIT | 0x23 | EXG1 CH1 16 Bit
EXG_ADS1292R_1_CH2_16BIT | 0x24 | EXG1 CH2 16 Bit
EXG_ADS1292R_2_CH1_16BIT | 0x25 | EXG2 CH1 16 Bit
EXG_ADS1292R_2_CH2_16BIT | 0x26 | EXG2 CH2 16 Bit
STRAIN_HIGH | 0x27 | Bridge Amp High
STRAIN_LOW | 0x28 | Bridge Amp Low



</body>

</html>

**For the 3R we plan to support all the channels above. If it helps I am attaching a [link](https://github.com/ShimmerEngineering/Shimmer-C-API/blob/242fbe95d0663f7fba673b82488c04d7779000bc/ShimmerAPI/ShimmerAPI/ShimmerBluetooth.cs#L2868) to our c# api where we parse the inquiry response (channel IDs) , it might help serve as a reference for the number of bits/endianess etc if required. 

![Image](https://github.com/user-attachments/assets/fa2c950c-eb95-4855-add8-bcbde70dda92)

I hope the above helps, apologies for the delay in reply.

**Comment by lumagi** [comment]
Thank you for offering. I haven't forgotten about this, I hope I will get to it over the next two weeks.

**Comment by lumagi** [comment]
I have done a bit of work renaming the channel types, if you want to take a look at #27 . I will try to introduce the new `HardwareRevision` class soon.

**Comment by SimWalther** [comment]
Hi, first of all thank you for the work you've put into this useful library.
I think the gyroscope data isn't being read properly. The endianness appears to be wrong even though it seems to be defined correctly in the device revision for Shimmer3r. When I plot the values, they oscillate between min and max values, but when I reverse the endianness manually, I get values that make sense.
Additionally, I'm experiencing an issue with pressure data: I get a "queue empty" error when the temperature sensor group is activated, even though I'm not reading data from those sensors afterward.

**Comment by lumagi** [comment]
Hi Simon,
That can very well be. Can you provide some more details about what version of the code you're currently using and what API? Bluetooth should be working with the new revisions but Reader and Dock are currently hard coded for revision 3.

**Comment by SimWalther** [comment]
Hi @lumagi,
The code I used is from the December 25th version of the hw_revision branch with Bluetooth API and Shimmer3r.
I hadn't seen that you updated this branch over the weekend. I'll test again with the latest changes and get back to you.

**Comment by lumagi** [comment]
Great, please do and let me know. There are currently no specific test cases for revision 3R, so there might be some bugs hiding in some places.

**Comment by SimWalther** [comment]
I checked and the good news is that the gyroscope is now working :)
Unfortunately, I still have an error when the pressure and temperature group is activated for the device.
The error is:

```
Traceback (most recent call last):
  File "/usr/lib/python3.13/threading.py", line 1043, in _bootstrap_inner
    self.run()
    ~~~~~~~~^^
  File "/usr/lib/python3.13/threading.py", line 994, in run
    self._target(*self._args, **self._kwargs)
    ~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/pi/Desktop/shimmer/.venv/lib/python3.13/site-packages/pyshimmer/bluetooth/bt_api.py", line 505, in _run_readloop
    self._bluetooth.process_single_input_event()
    ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^
  File "/home/pi/Desktop/shimmer/.venv/lib/python3.13/site-packages/pyshimmer/bluetooth/bt_api.py", line 292, in process_single_input_event
    self._process_resp_from_queue()
    ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^
  File "/home/pi/Desktop/shimmer/.venv/lib/python3.13/site-packages/pyshimmer/bluetooth/bt_api.py", line 261, in _process_resp_from_queue
    cmd, return_obj = self._resp_queue.get_nowait()
                      ~~~~~~~~~~~~~~~~~~~~~~~~~~~^^
  File "/usr/lib/python3.13/queue.py", line 234, in get_nowait
    return self.get(block=False)
           ~~~~~~~~^^^^^^^^^^^^^
  File "/usr/lib/python3.13/queue.py", line 199, in get
    raise Empty
_queue.Empty
```

In the `_process_resp_from_queue`, if I print the `peek` value, I get `0x69`, so it's not recognized as a `DataPacket`.

**Comment by lumagi** [comment]
It looks like something's messing up the input stream. My spontaneous assumption would be that something is wrong with the channel data types. That causes the incorrect amount of data to be read from the stream and the reader goes out of sync, reading garbage.

Can you open a new issue for this?
When you open the issue, can you make a trace of the serial communication with the Shimmer? You can do so by plugging interceptty in between: https://github.com/geoffmeyers/interceptty

**Comment by lumagi** [comment]
@JongChern is the sdlog binary format final? Sebastian would like to update the reading routines in #32 , which would potentially be affected by the new header.

**Comment by JongChern** [comment]
hi @lumagi there was a switch between the two mags, we have elected to use the LIS2MDL as the main magnetometer this has resulted in the following changes below

<img width="2498" height="1643" alt="Image" src="https://github.com/user-attachments/assets/275a9836-aa55-416d-8c10-056a32340403" />

**Comment by lumagi** [comment]
@JongChern Currently, the ShimmerDock class is hardcoded for the Shimmer3. Is there a way to determine the shimmer hardware revision via the Dock UART?

Is the following repository the current source of truth for the firmware for the Shimmer3 and Shimmer3R?
https://github.com/ShimmerResearch/log-and-stream-common

**Comment by JongChern** [comment]
@lumagi would the following help:-

<img width="2248" height="1585" alt="Image" src="https://github.com/user-attachments/assets/fbe4eaa0-c0aa-40f0-a27a-c14bec38a8d9" />

https://github.com/ShimmerResearch/log-and-stream-common/blob/f546c334d67d1f718e24724d06c1abe722141468/Extras/python_scripts/Docked%20commands/test_docked_cmds.py#L42

**Comment by lumagi** [comment]
@JongChern I just implemented the change on #40 , would you be willing to test? If you do, could you please provide the raw binary return value of the read_hw_sw_ver command?

**Comment by JongChern** [comment]
hi, looks good. See comment :-

https://github.com/seemoo-lab/pyshimmer/pull/40#issuecomment-4302099878

for the raw binary values it would basically be the same format as a Shimmer3, but if you want to test specifically for the 3R then the HW type will return as 10

**Comment by JongChern** [comment]
@lumagi any thoughts on creating a new release that has this new Shimmer3R support?

**Comment by lumagi** [comment]
You're right, it probably makes sense to release something soon. In the current state, the reader API is not compatible to the 3R file format, right?

**Comment by JongChern** [comment]
@lumagi  i am currently making updates to get 3R file format (binary file) supported. I will give an update next week.
